org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=/Users/seif/Library/Java/JavaVirtualMachines/corretto-17.0.12/Contents/Home
# Set these in your local gradle.properties or environment variables
#gpr.user=YOUR_GITHUB_USERNAME
#gpr.key=YOUR_GITHUB_TOKEN
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
